// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodexVS22
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodexVS22.4b168616-cd69-4ffb-9f78-bbab9d6cf52f";
        public const string Name = "CodexVS22";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Curt Petricca";
        public const string Tags = "";
    }
}
